### ISSUE TITLE
Add API for olmod server browser

### ISSUE THREAD

**Issue by roncli** [overload-development-community/olproxy.otl.gg#40]
![API](https://cdn.discordapp.com/attachments/661457345129480240/677055711724699648/unknown.png)

**Comment by tobiasksu** [comment]
Here's the current version I'm using with some of the redundancy removed.  Feel free to modify these to match up more with your existing tracker code and/or ServerStatLog.GetData().  I'm not currently displaying anything with loadout/player names/spawn timers etc but could easily do so if it's not too computationally/bandwidth intensive to include in the API.  (i.e. array of playerName instead of currentPlayers int would be cleaner)

`[{
	"ip": "13.78.149.56",
	"name": "roncli.com us-westcentral",
	"serverNotes": "Cheyenne, WY, USA - Azure D2s v3 - Use !servers on OTL or Overload Discords to start.",
	"matchNotes": "OTL match",
	"gameStarted": "2020-02-12T07:24:08.977Z",
	"lastSeen": "2020-02-12T05:53:54.859Z",
	"currentPlayers": 4,
	"maxPlayers": 16,
	"matchLength": 20,
	"mapName": "Vault",
	"mode": "TEAM ANARCHY",
	"jip": 0,
	"hasPassword": 0,
	"online": 1
}]`
